pr: none

stages:
  - stage:
    displayName: Build
    jobs:
      - template: azure-build-job-template.yml
        parameters:
          name: MacOSX14_Release
          vmImage: 'macOS-10.14'
          cmakeConfigArgs: '-G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release'
      - template: azure-build-job-template.yml
        parameters:
          name: MacOSX14_Debug
          vmImage: 'macOS-10.14'
          cmakeConfigArgs: '-G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug'
      - template: azure-build-job-template.yml
        parameters:
          name: Win64_VS2017_Release
          vmImage: 'VS2017-Win2016'
          cmakeConfigArgs: '-G "Visual Studio 15 2017 Win64"'
          cmakeBuildArgs: '--config Release'
      - template: azure-build-job-template.yml
        parameters:
          name: Win64_VS2017_Debug
          vmImage: 'VS2017-Win2016'
          cmakeConfigArgs: '-G "Visual Studio 15 2017 Win64"'
          cmakeBuildArgs: '--config Debug'
      - template: azure-build-job-template.yml
        parameters:
          name: Win64_VS2019_Release
          vmImage: 'windows-2019'
          cmakeConfigArgs: '-G "Visual Studio 16 2019" -A x64'
          cmakeBuildArgs: '--config Release'
      - template: azure-build-job-template.yml
        parameters:
          name: Win64_VS2019_Debug
          vmImage: 'windows-2019'
          cmakeConfigArgs: '-G "Visual Studio 16 2019" -A x64'
          cmakeBuildArgs: '--config Debug'

  - stage:
    displayName: Package
    jobs:
      - job: UploadGitHubRelease
        pool:
          vmImage: windows-2019
        steps:
        # Download all the artifacts uploaded by the jobs in the Build stage.
        - download: current
          targetPath: $(Build.ArtifactStagingDirectory)
        # Create a GitHub release containing the artifacts.
        - task: GitHubRelease@0
          inputs:
            gitHubConnection: GitHubPAT
            action: edit
            target: $(Build.SourceVersion)
            tagSource: manual
            tag: WAVM-LLVM-$(Build.BuildNumber)
            title: WAVM-LLVM-$(Build.BuildNumber)
            assets: $(Build.ArtifactStagingDirectory)/*
            releaseNotesSource: input
            releaseNotes:
            addChangeLog: false