parameters:
  buildConfiguration: Release
  name: ''
  vmImage: 'VS2017-Win2016'
  cmakeArgs: '-G "Visual Studio 15 2017 Win64"'
  vsPlatform: x64


jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    timeoutInMinutes: 120
    steps:
    - checkout: self
      submodules: recursive

    - task: CMake@1
      displayName: Configure LLVM
      inputs:
        workingDirectory: '$(Build.ArtifactStagingDirectory)/llvm-project/llvm'
        cmakeArgs: '${{ parameters.cmakeArgs }} -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)/install/llvm -DLLVM_TARGETS_TO_BUILD=X86;AArch64 -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_GO_TESTS=OFF -DLLVM_INCLUDE_TOOLS=OFF -DLLVM_INCLUDE_UTILS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_OPTIMIZED_TABLEGEN=ON $(Build.SourcesDirectory)/llvm-project/llvm/'

    - task: VSBuild@1
      displayName: Build LLVM
      inputs:
        solution: '$(Build.ArtifactStagingDirectory)/llvm-project/llvm/INSTALL.vcxproj'
        platform: ${{ parameters.vsPlatform }}
        configuration: ${{ parameters.buildConfiguration }}

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(Build.ArtifactStagingDirectory)/install/llvm
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.name }}.zip

    - publish: $(Build.ArtifactStagingDirectory)/${{ parameters.name }}.zip
      artifact: ${{ parameters.name }}