jobs:
  - template: azure-windows-build-job-template.yml
    parameters:
      name: Win64_VS2017_Release
      buildConfiguration: Release
      vmImage: 'VS2017-Win2016'
      cmakeArgs: '-G "Visual Studio 15 2017 Win64"'
  - template: azure-windows-build-job-template.yml
    parameters:
      name: Win64_VS2017_Debug
      buildConfiguration: Debug
      vmImage: 'VS2017-Win2016'
      cmakeArgs: '-G "Visual Studio 15 2017 Win64"'
  - template: azure-windows-build-job-template.yml
    parameters:
      name: Win64_VS2019_Release
      buildConfiguration: Release
      vmImage: 'windows-2019'
      cmakeArgs: '-G "Visual Studio 16 2019" -A x64'
  - template: azure-windows-build-job-template.yml
    parameters:
      name: Win64_VS2019_Debug
      buildConfiguration: Debug
      vmImage: 'windows-2019'
      cmakeArgs: '-G "Visual Studio 16 2019" -A x64'
