parameters:
  name: ''
  vmImage: 'macOS-10.14'
  cmakeConfigArgs: '-G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo'
  cmakeBuildArgs: ''

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    timeoutInMinutes: 120
    steps:
    - checkout: self
      submodules: recursive
      fetchDepth: 1

    - task: CMake@1
      displayName: Configure LLVM
      inputs:
        workingDirectory: '$(Build.ArtifactStagingDirectory)/llvm'
        cmakeArgs: '${{ parameters.cmakeConfigArgs }} -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)/install/llvm -DLLVM_TARGETS_TO_BUILD=X86;AArch64 -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_GO_TESTS=OFF -DLLVM_INCLUDE_TOOLS=OFF -DLLVM_INCLUDE_UTILS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_OPTIMIZED_TABLEGEN=ON $(Build.SourcesDirectory)/llvm-project/llvm/'

    - task: CMake@1
      displayName: Build LLVM
      inputs:
        workingDirectory: '$(Build.ArtifactStagingDirectory)/llvm'
        cmakeArgs: '--build . --target install ${{ parameters.cmakeBuildArgs }} --parallel 2'

    # The LLVM install doesn't include PDB files, so manually copy them to the install directory
    - task: CopyFiles@2
      displayName: Copy PDBs
      inputs:
        sourceFolder: $(Build.ArtifactStagingDirectory)/llvm
        contents: '**/*.pdb'
        targetFolder: $(Build.ArtifactStagingDirectory)/install/llvm

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(Build.ArtifactStagingDirectory)/install/llvm
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.name }}.zip

    - publish: $(Build.ArtifactStagingDirectory)/${{ parameters.name }}.zip
      artifact: ${{ parameters.name }}